models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.secret_key = "secret key"
app.config["SQLALCHEMY_DATABASE_URI"] = "mysql://root:123456@localhost/contactsdb"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db


contacts = Blueprint("contacts", __name__)


@contacts.route("/")
def index():
    contacts = Contact.query.all()
    return render_template("index.html", contacts=contacts)


@contacts.route("/new", methods=["POST"])
def add_contact():
    fullname = request.form["fullname"]
    email = request.form["email"]
    phone = request.form["phone"]

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()

    flash("Contact added sucess!!!!")

    return redirect(url_for("contacts.index"))


@contacts.route("/update/<id>", methods=["POST", "GET"])
def update(id):
    contact = Contact.query.get(id)

    if request.method == "POST":
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]

        db.session.commit()

        flash("Contact update a sucess!!!!")

        return redirect(url_for("contacts.index"))
    else:
        contact = Contact.query.get(id)
        return render_template("update.html", contact=contact)


@contacts.route("/delete/<id>")
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()

    flash("Contact deleteded sucess!!!!")

    return redirect(url_for("contacts.index"))


@contacts.route("/about")
def about():
    return render_template("about.html")

templates/about.html
{% extends 'layouts.html' %}

{% block body %}


<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero rem, quibusdam obcaecati sed odit possimus quo quidem
    quae delectus, vitae doloribus cumque in vero distinctio perspiciatis, officiis hic ratione voluptatum?</p>



{% endblock %}

templates/index.html
{% extends 'layouts.html' %}

{% block body %}





{% with messages = get_flashed_messages() %}

{% if messages %}

{% for message in messages %}
{{ message }}
{% endfor %}

{% endif %}

{% endwith %}




<form action="/new" method="POST" class="card bg-primary text-light">


    <div class="card-body p-4">
        <div class="mb-3">

            <input type="text" name="fullname" placeholder="Write your fullname">
        </div>

        <div class="mb-3">
            <input type="email" name="email" placeholder="Write your email?">
        </div>



        <input type="tel" name="phone" placeholder="Write your phone?">

        <button>Save</button>
    </div>

</form>

<div>
    {% for contact in contacts %}

    <div>
        <h5>{{contact.fullname}}</h5>
        <div>
            <a href={{ url_for('contacts.update', id=contact.id) }}>Update</a>
            <a href={{ url_for('contacts.delete', id=contact.id) }}>Delete</a>
        </div>
        <p>{{contact.email}}</p>
        <p>{{contact.phone}}</p>
    </div>

    {% endfor %}
</div>

{% endblock %}

templates/layouts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FLASK CRUD SQLALCHEMY</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

    {% include('partials/_navbar.html') %}

    <div class="container p-2">
        {% block body %}
        {% endblock %}
    </div>


</body>

</html>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">CRUD FLASK SQLALCHEMY</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/about">About <span class="sr-only">(current)</span></a>
            </li>

        </ul>
    </div>
</nav>

templates/update.html
{% extends 'layouts.html' %}

{% block body %}


<form action="/update/{{ contact.id }}" method="POST">
    <input type="text" name="fullname" placeholder="Write your fullname?" value="{{ contact.fullname }}">
    <input type="email" name="email" placeholder="Write your email?" value="{{ contact.email }}">
    <input type="tel" name="phone" placeholder="Write your phone?" value="{{ contact.phone }}">

    <button>Save</button>
</form>

{% endblock %}